name: Update
on:
  push:
    branches:
      - master
    paths:
      - readme.md
      - .github/workflows/hub.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - 
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ vars.DOCKER_USERNAME || secrets.DOCKER_USERNAME || secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ vars.DOCK_REPO || secrets.DOCK_REPO || secrets.DOCKHUB_REPO || 'dockurr/dnsmasq' }}
        short-description: ${{ github.event.repository.description || 'Docker container for dnsmasq' }}
        readme-filepath: ./readme.md
